### ISSUE TITLE
infinite loop in win10 count.cues_outcomes()

### ISSUE THREAD

**Issue by MegamindHenry** [quantling/pyndl#188]
### What you were trying to do
tried to follow instructions on "A minimal workflow example" section

### What actually happened
an infinite loop with error messages showed up

### How to reproduce

* Step 1
follow instructions on "A minimal workflow example" section
* Step 2
run scripts
```
from pyndl import count
freq, cue_freq_map, outcome_freq_map =
count.cues_outcomes(event_file_name='doc/data/levent.tab.gz')
```
* Step 3
errors like:
```
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.    is not
going to be frozen to produce an executable.''')
```

### System details

failed on running `python -c "import pyndl; pyndl.sysinfo()"`
```
(base) C:\Users\hakun>python -c "import pyndl; pyndl.sysinfo()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\hakun\AppData\Roaming\Python\Python37\site-packages\pyndl\__init__.py", line 57, in sysinfo
    uname = os.uname()
AttributeError: module 'os' has no attribute 'uname'
```
```
Python 3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.machine()
'AMD64'
>>> platform.version()
'10.0.19041'
>>> platform.platform()
'Windows-10-10.0.19041-SP0'
>>> platform.uname()
uname_result(system='Windows', node='DESKTOP-IC3FMLJ', release='10', version='10.0.19041', machine='AMD64', processor='AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD')
>>> platform.system()
'Windows'
>>> platform.processor()
'AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD'
```

**Comment by derNarr** [comment]
Thank you for you bug report. The code you used to extract the platform information will be added to the sysinfo() function.

As I have very limited experience with running things on Windows, I first have to look into the error message. If you have any clue or got it to run, please let me know as well.

**Comment by derNarr** [comment]
I looked into this issue again. As far as I understand the problem on Windows the `multiprocessing` module uses spawn and needs an "if-clause safe guard" (whatever this means in detail).

Can you try to change your script in the following way and run it then?

```
from pyndl import count

if __name__ == "__main__":
    freq, cue_freq_map, outcome_freq_map = count.cues_outcomes(event_file_name='doc/data/levent.tab.gz')
```

If this helps, we should add some additional information into the documentation, but don't need to change the code of pyndl itself.
